name = "blazar/hydra-pay"
version = "0.0.0"
compiler = "v1.1.4"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'blazar/hydra-pay'"

[repository]
user = "blazar"
project = "hydra-pay"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[config.default]
add_funds_min_lovelace = 1000000
