const DBStatus = {
  INITIALIZING: 'INITIALIZING',
  MERGING: 'MERGING',
  COMMITTING: 'COMMITTING',
  AWAITING: 'AWAITING',
  RUNNING: 'RUNNING',
  DECOMMITING: 'DECOMMITING',
  CLOSING: 'CLOSING',
  CLOSED: 'CLOSED',
  FAILED: 'FAILED',
} as const;

type DBStatus = keyof typeof DBStatus;

export { DBStatus };
