name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - "*"
    

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "src/.nvmrc"
          cache: "npm"
          cache-dependency-path: "src/package.json"

      - name: Install dependencies
        run: npm ci
        working-directory: ./src

      - name: Run ESLint and fix
        run: npm run lint:fix
        working-directory: ./src

      - name: Format with Prettier
        run: npm run format
        working-directory: ./src

      - name: Check for remaining ESLint errors
        run: npm run lint
        working-directory: ./src

      - name: Check for remaining formatting issues
        run: npm run format:check
        working-directory: ./src
